# Generated by Django 5.1 on 2024-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('skills', models.CharField(max_length=255)),
                ('aboutme', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('adsress', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=355)),
                ('follow_me_on_facebook', models.CharField(max_length=255)),
                ('follow_me_on_twitter', models.CharField(max_length=255)),
                ('follow_me_on_google', models.CharField(max_length=255)),
                ('follow_me_on_instagram', models.CharField(max_length=255)),
            ],
        ),
    ]
