# Generated by Django 5.1 on 2024-08-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='adsress',
            new_name='addsress',
        ),
    ]
