# Generated by Django 5.1 on 2024-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_rename_adsress_resume_addsress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='addsress',
            new_name='address',
        ),
    ]
